<?php

namespace AppBundle\Repository;

/**
 * IndentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndentRepository extends \Doctrine\ORM\EntityRepository
{
}
